// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"github.com/tabed23/social-media-api/graph/models"
)

type Mutation struct {
}

type NewUserInput struct {
	Username       string  `json:"username"`
	Email          string  `json:"email"`
	Name           string  `json:"name"`
	Bio            *string `json:"bio,omitempty"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	Password       string  `json:"password"`
}

type Query struct {
}

type UserMutationResponse struct {
	User   *models.User `json:"user,omitempty"`
	Errors []string     `json:"errors"`
}
