// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type NewUserInput struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	Name           string `json:"name"`
	Bio            string `json:"bio"`
	ProfilePicture string `json:"profilePicture"`
	Password       string `json:"password"`
}

type Query struct {
}
