// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Mutation struct {
}

type NewPostInput struct {
	Content string `json:"content"`
}

type NewUserInput struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	Name           string `json:"name"`
	Bio            string `json:"bio"`
	ProfilePicture string `json:"profilePicture"`
	Password       string `json:"password"`
}

type Query struct {
}

type UpdatePostInput struct {
	Content   *string    `json:"content,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UpdateUserInput struct {
	Username       *string    `json:"username,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Bio            *string    `json:"bio,omitempty"`
	ProfilePicture *string    `json:"profilePicture,omitempty"`
	Password       *string    `json:"password,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}
